### ISSUE TITLE
Linkedin url

### ISSUE THREAD

**Issue by chris74a** [simov/grant#119]
Hello, 
I do not know if you are always supporting this repo, but the linkedin url for v2 is https://www.linkedin.com/oauth/v2/authorization

Maybe it will save much time for others! ;o)

**Comment by simov** [comment]
Thanks @chris74a I'll have a look.

**Comment by simov** [comment]
@chris74a I've updated the URLs for v2 https://github.com/simov/grant/commit/405e9c8aab6d6bd99e75e7188b072e08e26a0048

Note that you have to use `/connect/linkedin2` when logging in. The reason why is because `linkedin` was used for v1, and even though it's no longer supported, it still works for people having old apps. I'll have to remove it at some point.
