### ISSUE TITLE
Not clear how to pass constant query params to authorize_url

### ISSUE THREAD

**Issue by ohjames** [simov/grant#137]
The atlassian oauth provider requires you to always pass `audience=api.atlassian.com&response_type=code&prompt=consent` to the "authorize url".

Now you could set `custom_parameters` to `['audience', 'response_type', 'prompt']` via `oauth.json` and then the user would always need to set `custom_params` to `{audience: 'api.atlassian.com', response_type: 'code', prompt: 'consent' }` in their configuration, but it doesn't seem worthwhile to make the user do this.

Does grant support a way to encode these constants in `oauth.json`? I looked at the existing file and nothing seems clear. If it does support this, could the documentation be updated to make it clear how to do this?

Thanks!

**Comment by simov** [comment]
I don't see a problem with specifying a few keys in your configuration. Also note that `response_type` is set internally, so you don't have to set that explicitly. Can you give the link to the documentation you are looking at for Atlassian?

**Comment by ohjames** [comment]
@simov It's here: https://developer.atlassian.com/cloud/jira/platform/oauth-2-authorization-code-grants-3lo-for-apps/

I guess it's okay to make the user set `audience` and `prompt` to the constant values, but you can guarantee a lot of people won't realise it's necessary. It makes the library a bit less plug and play.

**Comment by simov** [comment]
Grant strives to be generic, and that comes at a price. Being generic makes it flexible, but the downside is that the user have to do some additional work for some of the providers.

The `custom_params` are called like that because they are not part of the OAuth spec. Supporting anything outside of the spec, like provider specific defaults is not feasible for this module. Imagine having to maintain 200 providers with their quirks, and keep in mind that these platforms change over time.

Other than that I appreciate your feedback, and I totally agree with you that this can cause issues for some users.

Btw `atlassian` seems to be missing from oauth.json as a provider. Want to become a contributor? Feel free to add it :+1:

**Comment by ohjames** [comment]
@simov Makes sense, and thanks for responding so quickly. As easy as it would be to support constant query params, it does sound like the start of a slippery slope. I'll open a PR with `atlassian` added to `oauth.json` after testing it out. They've only added the functionality very recently.
