### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by tecky-dev** [simov/grant#150]
I think this package is awesome for educational purpose since it is much more generic than the passportjs library. I wonder if there is any plan to have Typescript support?

**Comment by simov** [comment]
Not sure if you ask about migrating the project to .ts files, or just adding separate type definitions file, so I'll answer both:

Migrating the project to .ts files - no. I'm not interested in that. I mean, I'm not interested in making what's arguably the best dynamic language into a strict one. Otherwise I agree that beginners should start with a strictly typed language just to learn how to program, but there are plenty of great typed languages out there that you can start with.

Adding a separate type definitions file - probably not. The only public interface that Grant exposes is a function that accepts your configuration, that is a JSON file that you most probably load from a file. What it returns is whatever your HTTP framework of choice expects. The rest are internals, and I'd argue that they are pretty easy to understand, even though they are in plain old vanilla JavaScript.

**Comment by tecky-dev** [comment]
I was thinking the second one. But thanks for clarifying that. As I mentioned above I think the package is a much better alternative than passportjs since it does not impose unnecessary assumption on the flow of the program which makes it easier to reason than passportjs.  Keep up the good work! Thank you!

**Comment by guyellis** [comment]
@simov I was wondering if you would accept a PR to add a `.d.ts` definition file for TypeScript to this repo based on one that I've created and started using in another project: https://github.com/guyellis/plant/blob/master/lib/types/grant.d.ts

This shouldn't get in the way of anything that you are doing in this (amazing) project and would benefit other Typescript users of this project.

The alternative location for this type of file is the DefinitelyTyped project. My feeling is that it's better if the types are in the original project as it is easier to maintain them and keep them insync with the original code.

Thoughts?

**Comment by simov** [comment]
TypeScript type definitions were added and published in Grant v5.4.6

You can check out the type definitions [here](https://github.com/simov/grant/blob/master/grant.d.ts). I also created a [helper repository](https://github.com/simov/grant-types) containing examples and additional type definitions specific to different HTTP frameworks.

Let me know what you think.

**Comment by tecky-dev** [comment]
Thank you ! The types are working great. 

Except the type of the following expression is `ExpressMiddleware & GrantInstance`.

```typescript
const grantExpress = grant.express({
    "defaults":{
        "origin": "http://localhost:8080",
        "transport": "session",
        "state": true,
    },
})
```

It is going to fail the type checking when we are using it with express since `Express` is expecting a `express.RequestHandler`.

```typescript
app.use(grantExpress);
```

The type error is as follow

```
const grantExpress: ExpressMiddleware & GrantInstance
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'ExpressMiddleware & GrantInstance' is not assignable to parameter of type 'PathParams'.
      Type 'ExpressMiddleware & GrantInstance' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 25 more.ts(2769)
index.d.ts(69, 5): The last overload is declared here.
```

It works if I manually cast it to `express.RequestHandler`.

```typescript
app.use(grantExpress as express.RequestHandler);
```

**Comment by simov** [comment]
Interesting, I have that exact same example and it works on my end. I can't import and extend all framework specific types inside the main repo, and that's why I picked a definition that seemed to be working. Can you share your tsconfig? I'm using the [helper repo](https://github.com/simov/grant-types) for testing, and currently I'm trying out different ts configurations because other people reported other issues as well.

**Comment by tecky-dev** [comment]
Here is my `tsconfig.json`.

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "lib": ["es6", "dom"],
        "sourceMap": true,
        "allowJs": true,
        "jsx": "react",
        "esModuleInterop":true,
        "moduleResolution": "node",
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true
    },
    "exclude": [
        "node_modules",
        "build",
        "scripts",
        "*.js",
        "frontend",
        "public"
    ]
}
```


My Typescript version is `v3.1.6`.

**Comment by alexnault** [comment]
I had the same TS error as @tecky-dev.

Updating `@types/express` and most importantly `@types/express-serve-static-core` to the latest version fixed the issue.

```
@types/express@4.17.3 => @types/express@4.17.9
@types/express-serve-static-core@4.17.3 => @types/express-serve-static-core@4.17.13
```

**Comment by simov** [comment]
@tecky-dev I published a small fix regarding the Express middleware typings in v5.4.9 I also updated the [examples](https://github.com/simov/grant-types). Can you give it a try?
