### ISSUE TITLE
Dynamic: HTTP using GET Not working

### ISSUE THREAD

**Issue by zerbzman** [simov/grant#164]
Hey,

I have a custom parameter that I am trying to set using a get request. I set my custom parameter {"force_login": false} in my config. Then I set my GET request to "connect/pco?force_login=true". Upon clicking the link, the parameter "force_login" never gets overridden to true and the call to the provider is the same as the default. If I log req.session.grant.dynamic right after, it says force_login: 'true'.

I have also tried using dynamic: ["force_login"] in my config but still no luck

Am I missing something?

**Comment by simov** [comment]
Hi,

You should have something like:

```json
{
  "pco": {
    "custom_params": {"force_login": false},
    "dynamic": ["custom_params"]
  }
}
```

Then you have to pass your custom parameter as `custom_params[force_login]=true` but it have to be URL Encoded as well:

```
/connect/pco?custom_params%5Bforce_login%5D%3Dtrue
```

Let me know if it works for you.

Also note that there was a bug in the path matching regexp for Express and Koa that I just fixed and published as v5.0.1 It might not be related to this issue but I recommend you to install it just in case.

**Comment by zerbzman** [comment]
Hey,

So if I put `/connect/pco?custom_params%5Bforce_login%5D%3Dtrue` as my link then it didn't work and when I checked the dynamic variable it was `dynamic: { custom_params: { force_login: '' } }`

When I put `connect/pco?custom_params[force_login]=true` as my link then it worked.

**Comment by simov** [comment]
Seems like a typo on my end, you shouldn't encode the equal sign, so that is correct. The browser will encode the square brackets, you can check that in the [showcase app](https://grant.outofindex.com). 

If you go there and choose `google` for example, then pick a custom parameter and open up the network tab, also make sure Preserve log is checked. Then after clicking login you can check back what was sent as URL encoded post body to the `/connect` route.

**Comment by zerbzman** [comment]
Awesome, thanks!
