### ISSUE TITLE
Remove dynamic parameters stored in session on subsequent auth

### ISSUE THREAD

**Issue by adamsea** [simov/grant#186]
Hello,

I had a question about an issue that I'm experiencing with Grant right now (using grant-express 4.5.2, but it appears to function the same way in 5.x) ... when I authenticate to a `/connect` based endpoint that has been configured to use `dynamic` parameters, they will be properly stored into the session. However, on subsequent auth requests to other providers, the `dynamic` config sticks around in the session unless manually removed. This is true even if I explicitly unset `dynamic` configuration using an empty array in the provider.

After looking through the code I believe it has to do with the fact that every `connect` function also uses `init` in lib/config, which in turn is using a deep-copy of the previous session and only overwriting session properties that were set to some sort of "truthy" value (or not in reserved words .. e.g. "dynamic" is in there)

So my question really is .... is there any way to unset these lingering session values on connect, or is it considered best practice to unset them manually on callback?

Thanks for your help!
Eric

edit: Relevant code is:
* (request) https://github.com/simov/grant/blob/master/lib/request.js#L22
* (config) https://github.com/simov/grant/blob/master/lib/config.js#L185
* (init) https://github.com/simov/grant/blob/master/lib/config.js#L144

**Comment by simov** [comment]
Hi @adamsea, thanks for the question.

First of all the lingering values you are mentioning are not present on `/connect`:

https://github.com/simov/grant/blob/34e202267c250c6bab1d34fde172efc6a1bc343d/lib/request.js#L14

What this tells us is that unless you are accessing the `redirect_uri` you start with a fresh empty session on `/connect`.

That being said at some point I had the idea of reusing session, which was a mistake, and later implemented as [Dynamic State](https://github.com/simov/grant#dynamic-state) instead. So for a few 4.x versions, the Express handler only, was not initialized with empty session object. In case you are using some of those version I encourage you to upgrade. Even if you can't upgrade to 5.x immediately, you can use 4.7.0 instead:

https://github.com/simov/grant/blob/7f46640d2ae8b278ea4c9d0f01840818b1989607/lib/consumer/express.js#L32

Let me know if that fixes the issue for you.

**Comment by simov** [comment]
The easiest way to test this is as follows:

1. Navigate to the `examples/handler-express`
2. Set your `key` and `secret` for Google in `config.json`, your app's redirect URI should be `http://localhost:3000/connect/google/callback`, also add `dynamic: ['state']` for Google to enable Dynamic Override
3. In `express-session.js` print the entire `req.session.grant` object instead
4. `npm install` and run `node express-session.js` - this is the default one
5. Login like this `http://localhost:3000/connect/google?state=grant`
6. You will see the `dynamic` key printed at the end, that means `state` is in session
7. Login again but this time without using dynamic override `http://localhost:3000/connect/google`
8. In the end you will see that you have just the `provider` key in the session along with the response, that means you are using a clean session, not the one from the previous attempt

To be extra confident about this open up the Network tab in DevTools and enable Preserve Log. Login again using both URLs. You can check out the redirect URI, when using dynamic override you get back the state, otherwise it's not present. Again that means clean session on every connect.

Let me know if that makes sense or if I'm missing something.

**Comment by adamsea** [comment]
Hi @simov, thank you for the update! Yes that totally makes sense, and yes the connect URLs were coming out just fine. I did confirm that I'm in a version (4.5.2) where `req.session.grant` is being reused in the express handler initialization:
https://github.com/simov/grant/blob/v4.5.2/lib/consumer/express.js#L27

So I'll try updating to 4.7.0, and I'll let you know if I have any questions! Thanks for all your work on this project too, it's worked great for me!

**Comment by simov** [comment]
Closing for now, feel free to add more details here.

**Comment by adamsea** [comment]
I'm all set here - I upgraded to 4.7.0 last week and that solved the problem. Thanks again!
