### ISSUE TITLE
koa-grant: How to get the user info from session

### ISSUE THREAD

**Issue by zhiyelee** [simov/grant#20]
I want to find a way to get the user info from the session after login. 

For example:

```js
// suppose user have login
router.get('/demo', function *(next) {
  if (!this.session.grant) {
    this.redirect('/login');
  } else {
   // get the user info from DB which I saved after user login successfully,
   //    eg, saved  in `/hanlde_provider_callback
    user = yield getUserInfo(this.session.grant.userId);
  }
}
```

Seems I can't add a new property to session in the `/handle_provider_callback`, so I don't how to connect  the special session with the db item (I want to store users in my db). Do you have any idea?

Thank you.

**Comment by simov** [comment]
I'm not sure that I understand your exact scenario, but here is what you can do - just store the access token somewhere in your database and link it to your user data.

**Comment by zhiyelee** [comment]
@simov thank you.

What i want to do is, eg

* user login with a provider, like github
* `/connect/github/callback`  // seems grant set session here.
* `/handle_github_callback`  // I want to fetch and store user info here, for example link session with access token.

After the above step, the login user access `/demo` page, then how can I get the user info from DB, as far as i known, the `this.session` only contains
```json
{ grant: { provider: 'github', dynamic: {} } }
```

That means i can't find current users access token or any other useful information besides provider.

Maybe i stupid question, thank you for your time.

**Comment by simov** [comment]
By default Grant returns the result data from the OAuth flow as a querystring, that's why you see only a meta data in the session that's used internally by Grant during the OAuth flow.

If you want the result data returned in the session instead, you have to set `transport:'session'` under the `server` key in your configuration, take a look at the [configuration docs](https://github.com/simov/grant#configuration)

Let me know if that solves your problem.

**Comment by zhiyelee** [comment]
@simov That make sense to me. Thank you a lot!!
