### ISSUE TITLE
ES6 Modules with grant

### ISSUE THREAD

**Issue by tvvignesh** [simov/grant#203]
Hi. Thanks for making `grant`. I tried it and it works well for many OAuth2 providers. 

One question I had was regarding support for ES Modules. While I understand from the issues that you have decided not to support Typescript, I was wondering how to import grant as a ES6 module.

While `require('grant').fastify();` works, I wanted to go the standard route since `require` is not a standard and definitely not recommended in the future for Node.js with `mjs` support now in place.

**Comment by simov** [comment]
Here is the [basic example](https://github.com/simov/grant/blob/master/examples/transport-querystring/express.js) with Express using ES6 modules:

```js
import express from 'express'
import session from 'express-session'
import grant from '../../grant.js'
import config from './config.json'


express()
  .use(session({secret: 'grant', saveUninitialized: true, resave: false}))
  .use(grant.express(config))
  .get('/hello', (req, res) => {
    res.end(JSON.stringify(req.query, null, 2))
  })
  .get('/hi', (req, res) => {
    res.end(JSON.stringify(req.query, null, 2))
  })
  .listen(3000)
```

I run it with node 14:

```bash
node --experimental-json-modules express.mjs
```

The `--experimental-json-modules` flag is there because of the `.json` import. Also note that I renamed my file to `.mjs`

That being said I have to update the docs and the examples. Lets keep this issue open for now, also let me know if you have any other issues with it.

**Comment by tvvignesh** [comment]
Thanks @simov Will try it right away and report back. Btw, since I do this in TS, it does report a typings issue but that's fine.

<img width="604" alt="1" src="https://user-images.githubusercontent.com/1165845/98830008-e3f66180-245f-11eb-9838-5ffe6a32fe9c.png">

Will try it and let you know.

**Comment by simov** [comment]
I understand I'll look into that as well :+1:

**Comment by tvvignesh** [comment]
`import grant from 'grant';` did not work for me, it threw this error:

<img width="476" alt="1" src="https://user-images.githubusercontent.com/1165845/98832763-35ecb680-2463-11eb-88ea-a94f4ed38299.png">

Rather `import * as grant from 'grant';` did work well.

**Comment by simov** [comment]
TypeScript [type definitions](https://github.com/simov/grant/blob/master/grant.d.ts) landed in Grant v5.4.6

I also pushed a [separate repository](https://github.com/simov/grant-types) with a few examples and additional type definitions specific to different HTTP frameworks.

Let me know what you think.

**Comment by tvvignesh** [comment]
@simov Awesome! Will try it right away.

**Comment by tvvignesh** [comment]
@simov Just tried it out. The type defenition file which is now shipping with grant works great. I had to change `import * as grant from ` to `import grant from` now.

There are issues when using the framework specific types in my case though.

I use Fastify and I had a snippet like this:

```ts
import { FastifyPluginCallback } from 'fastify';

export const serverRoutes: FastifyPluginCallback = (server, options, done) => {
  server.get('/auth', options, (request, reply) => {
    reply.code(200).send({hello: 'world'});
  });
}
```

Now, if I add `import { FastifyRequest } from './grant-fastify';` and then use it for the types like this, it throws error:

<img width="337" alt="1" src="https://user-images.githubusercontent.com/1165845/99240205-2b933980-2822-11eb-9f85-1776f775806f.png">

stating 
```
Argument of type '(this: FastifyInstance<...>, request: FastifyRequest, reply: FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>) => void' is not assignable to parameter of type 'RouteHandlerMethod<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.
  Types of parameters 'request' and 'request' are incompatible.
    Property 'grant' is missing in type 'FastifyRequest<RouteGenericInterface, Server, IncomingMessage>' but required in type 'FastifyRequest'.ts(2345)
```

since I guess because I use `FastifyPluginCallback` it infers type of `request` as `(parameter) request: FastifyRequest<RouteGenericInterface, Server, IncomingMessage>` which does not match the types from the types provided by grant as specific to the framework.

I don't know if this can actually be resolved since the types of FastifyRequest as provided by Grant is going to be always different from what Fastify provides. Not sure if there is a way to extend the already available types to do this.

**Comment by simov** [comment]
Grant does not provide any framework specific type overrides. For Fastify specifically you can use these [type overrides](https://github.com/simov/grant-types/blob/master/types/fastify.d.ts). Note that you don't really need to extend the request and the response objects. The `grant` property there is used only for specific cases such as [dynamic state overrides](https://github.com/simov/grant/blob/master/examples/dynamic-state/fastify.js), and [state transport](https://github.com/simov/grant/blob/master/examples/transport-state/fastify.js). Also check out [this example](https://github.com/simov/grant-types/blob/master/test/frameworks.ts#L131-L135) see that there are no Fastify specific type overrides in that handler, and instead for both transport session and transport querystring you specify the Grant specific types explicitly.

Let me know if that makes sense.

**Comment by tvvignesh** [comment]
@simov Thanks for the clarification. Actually I am using the same type overrides which you have mentioned. If you see the [image](https://user-images.githubusercontent.com/1165845/99240205-2b933980-2822-11eb-9f85-1776f775806f.png) I attached above, the file `grant-fastify.d.ts` is nothing but `fastify.d.ts` (I have just renamed it) and I am picking the `FastifyRequest` from it which throws the error as mentioned above.

I did look at the example you linked as well and while that will definitely work in isolation, the problem will probably arise in trying to use Fastify specific types and the type overrides from grant together as mentioned in the image above.

Let me know if I am wrong. I will probably dig into this a bit more.

**Comment by simov** [comment]
Thanks for clarifying this. In this case I should probably remove the additional framework specific types from that repo. These were only meant for example purposes. I think only the Express types are too strict and require you to have extended request object for the grant session. Otherwise you can specify the Grant types [inside your handler](https://github.com/simov/grant-types/blob/master/test/frameworks.ts#L131-L135) instead. Alternatively you can extend the appropriate types yourself to get the types support directly on your request object.

**Comment by tvvignesh** [comment]
@simov Got it. I don't think this will be much of an issue anyways. Since this has been a remarkable improvement - From no typescript support to additional typedefs shipped along with Grant which can already help a lot. Feel free to close this issue whenever you want. Thanks.

**Comment by simov** [comment]
Sure, eventually we can have more robust extended types for the request/response objects that are going to work in all cases. But you should have all the tools (types) needed defined in Grant to extend them on your own. That being said probably a better documentation about each Grant type/interface might be helpful, but for now the best place for information are the examples in the grant-types repo.

Even if we have the correct request/response types for every framework, they can't be added to the main (this) repo, because it is supposed to be a generic one and not everyone would want to pull additional dependencies that are not needed otherwise.

**Comment by tvvignesh** [comment]
I understand. As you rightly mentioned, I don't think having types for every framework is feasible to both build and maintain and that is not expected anyways out of Grant as long as it can ship with its own types which you are already doing now. Infact, I don't see any other lib doing it either.

So, I don't think that should be an issue. I am totally fine with extending the types I need from Grant (that's what I do for other libs as well) and I am sure that its way easier for you as well.

**Comment by simov** [comment]
Sounds good. Note that you should probably only care about these interfaces:

```
GrantConfig
GrantProvider
GrantSession
GrantResponse
```

The config and the provider are the input data, and the session and the response are the output. You only need to use the session and the response in your extended types.

The rest are mainly for the serverless handlers right now:

```
GrantOptions
GrantSessionConfig
GrantSessionStore
GrantInstance
GrantHandlerResult
```

Where the options is the extended configuration data structure that in some cases might be useful for regular middlewares too, but most people probably won't use it with HTTP framework handlers.

The returned middleware type is only there to plug it into your HTTP framework of choice.

The reason why most of the properties are optional is because Grant can be configured in different ways and it also inherits configuration from other places such as the oauth.json file. So it's really hard to make anything required since it can brake perfectly valid configuration otherwise.

**Comment by tvvignesh** [comment]
Done. Will try it out. Thanks a lot for the clear and concise explanation. Currently I am using Grant as an OAuth proxy and storing all the authorized provider config in the DB and loading them dynamically as needed depending on the endpoint since I can dynamically add/update/remove providers without worrying about changing any code or reloading the server. Its working well so far.

**Comment by tvvignesh** [comment]
@simov Noticed something (it did not show up since I tried compiling just now). The grant type definition file, the types would need a comma in betwen them (interfaces don't need comma)

<img width="191" alt="1" src="https://user-images.githubusercontent.com/1165845/99276098-4bdaec80-2852-11eb-8832-aa172d4b6b74.png">

And another set of errors are thrown here:

<img width="584" alt="2" src="https://user-images.githubusercontent.com/1165845/99276136-55645480-2852-11eb-8c94-93c719244255.PNG">

**Comment by tvvignesh** [comment]
For the first error, I had to add `,` to solve them and for the second, I had to remove `?` (maybe you can fix it in the lib as well)

**Comment by tvvignesh** [comment]
Sent a PR here: https://github.com/simov/grant/pull/204

**Comment by simov** [comment]
Interesting, no idea where my commas went, as for the other one, I don't see that error TBH.

**Comment by tvvignesh** [comment]
@simov Tried 5.4.7 and it brings back the error I mentioned here: https://github.com/simov/grant/issues/203#issuecomment-725499408 

TS works if I do `import grant from 'grant'` but after transpilation, JS works only if there is `import * as grant from grant` 😅 Crazy times.

**Comment by simov** [comment]
I think I found a fix for the other one, it's `[provider: string]: GrantProvider | undefined` inside `GrantConfig`. As for the import, that's weird because I have a default export.

**Comment by tvvignesh** [comment]
@simov Great to hear that. To fix the exports, you can try this (tested it and works well on my end in both TS and JS when I do `import grant from 'grant'`):

You have only `module.exports` as of now in `grant.js`

Adding a default export fixes this issue:

That is from:

```ts
module.exports = grant
```

to 

```ts
grant.default = grant
module.exports = grant
```

You can see an example of `fastify-plugin` doing the same here: https://github.com/fastify/fastify-plugin/blob/master/plugin.js#L84

**Comment by simov** [comment]
Ok, published v5.4.8 with the last two fixes. You should be able to use the `strict` option now without patching the `GrantConfig`. As for the `esModuleInterop` that totally makes sense, I used that option myself, but I also added the `.default` import that you suggested.

**Comment by tvvignesh** [comment]
@simov Just installed v5.4.8 and tested it out with and without `esModuleInterop` and it works well now 👍

**Comment by simov** [comment]
Thanks for the help @tvvignesh, I really appreciate it :+1:
