### ISSUE TITLE
Add note that `callback` option is unused

### ISSUE THREAD

**Issue by gagoman** [simov/grant#21]
`redirect_uri` is built at https://github.com/simov/grant/blob/master/lib/utils.js#L6

So we cannot override callback.

Am I wrong?

Thx.

**Comment by simov** [comment]
The `redirect_uri` is what you specify as redirect uri in your OAuth application. That route should always have [this format](https://github.com/simov/grant#redirect-url) and it is used internally by Grant.

The `callback` option contains the final route where you get the results from the OAuth flow. Grant redirects you there after the `redirect_uri` was being hit. The reason for this is because by design Grant returns the result data in a certain way, no matter what provider you are using.

Let me know if there is anything unclear.

**Comment by gagoman** [comment]
Got it!

I'll read more about `OAuth 2`

Thx.
