### ISSUE TITLE
Where is app.js for the examples?

### ISSUE THREAD

**Issue by maxwellmckinnon** [simov/grant#246]
In the examples folder, not sure how to follow this instruction:

> 
> Server
> Start the server:
> 
> $ npm install
> $ node app.js

I checked every folder, and there are no app.js files in the examples

**Comment by simov** [comment]
It's `node the-http-framework.js` instead, like:

```bash
node express.js
node koa.js
```

and so on

**Comment by maxwellmckinnon** [comment]
I have since discovered passport and got that working because there was a working example a demo to copy. I am a total noobie though, what are some differences between grant and passport?

**Comment by simov** [comment]
All of the examples inside the examples folder are working, that's the point of having examples in the first place.

I used `node app.js` to document how you run an app with node. It's not practical to document every single handler separately as they are identical by design. Passport works only with express out of the box.

As for differences between the two, you can also check out this [article](https://dev.to/simov/oauth-simplified-2pbd).

I'm working on a wiki where I'm going to add more details outside of the main readme file which is only meant to be used as a quick reference guide.
