### ISSUE TITLE
Telegram Oauth

### ISSUE THREAD

**Issue by qertis** [simov/grant#287]
Can you please add support for telegram login?

Docs: https://core.telegram.org/api/auth
Example npm: https://www.npmjs.com/package/passport-telegram-official

**Comment by simov** [comment]
Hi @qertis, thanks for the links, I had a look and it seems like they are not using OAuth for authentication and instead some in-house protocol. Grant is an OAuth middleware, either OAuth 1.0a or OAuth 2.0 specifically the Authorization Code grant type + some OpenID Connect variations on top of it.

The reason why Passport has a middleware for Telegram is because they support other strategies too, other than OAuth.

Generally speaking Grant can accommodate for some variations, but if the protocol in question deviates too much from the OAuth protocol then it may fall out of scope for this module, which again, is strictly an OAuth middleware/proxy.

**Comment by qertis** [comment]
@simov ok, thanks.
