### ISSUE TITLE
Autodesk deprecated v1 (lib's current) oauth endpoints

### ISSUE THREAD

**Issue by TKDBB84** [simov/grant#291]
Autodesk oAuth2 implementation should migrate to v2 https://aps.autodesk.com/blog/migration-guide-oauth2-v1-v2

**Comment by simov** [comment]
Thanks for the feedback, I will definitely take a look.

**Comment by simov** [comment]
Autodesk provider is using Oauth2:

https://github.com/simov/grant/blob/6e0692dfdd83edbc4ee82629ba0fe8f986d5879d/config/oauth.json#L98-L103

What exactly isn't working?

**Comment by TKDBB84** [comment]
the `v1` endpoints will be disabled (timeline TBD).  The v2 endpoints change a few things in the contract, as an example:
`authentication/v1/gettoken` will move to `authentication/v2/token` and will no longer accept client_id/client_secret in the body of the request, but only as a Basic Auth header.  The v1 endpoints still work, but will be turned off eventually.  The migration guide provides all details.

**Comment by simov** [comment]
This was fixed in v5.4.22 https://github.com/simov/grant/commit/71445d69b740d59d516765230a9fb199180c01b6 Seems to be working as before. 

Note that even if this did not land on time you could have set the `authorize_url` and `access_url` URLs in your config to point to the correct URLs and then also the `token_endpoint_auth_method` option set to `client_secret_basic` to force the Basic authentication for the token endpoint.
