### ISSUE TITLE
Path prefix

### ISSUE THREAD

**Issue by arjanfrans** [simov/grant#47]
I have an api that I have mounted on an url like this:
`http://localhost/v2/social/`

My provider callbacks are configured like this:
`/v2/social/connect/twitter/done`

The callbacks in between however, do not know about the `/v2/social` part. These callbacks will come back to `http://localhost/connect/twitter/callback`.

I tried setting the `grant.server.host` to `localhost/v2/social`, but this didn't work. I dived a bit into the source code and added a quick fix to  be able to specify  `path` prefix options. I tried it with express and it seems to work. 

Here is what I did: https://github.com/arjanfrans/grant/commit/b18df7033fa8756ef8e18dadc8bcc0c9df880df1

In the config I then have something like this:

```
{
  server: {
    protocol: 'http',
    host: 'localhost',
    transport: 'session',
    path: '/v2/social'
  },
  twitter: {
    key: 'keyhere',
    secret: 'secrethere'
    callback: '/connect/twitter/done'
  }
}
```

To me it seems like a missing feature. It would be nice to see it integrated. I could work on a proper pull request if I have some time next week.

Thoughts?

Thanks.

**Comment by simov** [comment]
I think it should work out of the box if you set your `host` property to `localhost/v2/social` **and** mount Grant with that prefix:

```js
app.use('/v2/social', grant)
```

But I don't like using the `host` property like that, also I haven't tested it myself so it might not work. Either way I'll figure out the best way to add this feature these days. I'm also going to add a new example and I'll probably update the docs as well.

Thanks for contributing :+1:

**Comment by arjanfrans** [comment]
I didn't mount grant directly on the app, but have a wrapper around it with some custom middleware added. 

My server runs multiple express apps which are routed by Nginx, so express doesn't really know about the path.

For example, this is we proxy in Nginx:
* `/v2/social` -> express app A
* '/v2/api` -> express app B

For this use case, it didn't work.

**Comment by simov** [comment]
Got it, that makes sense. I have NginX running on my workstation. It will take me some time to prepare everything but eventually this feature will be added one way or another. Just FYI it will be released by the end of this month.

**Comment by simov** [comment]
@arjanfrans take a look at the [Path Prefix](https://github.com/simov/grant#path-prefix) section.

In your case you just have to:

1. Mount Grant as usual (without prefix).
2. Set the path prefix using the `path` configuration option under the `server` key (this option is used only for generating the `redirect_uri` that you specify for your OAuth app).
3. Prefix all your provider's `callback` configuration paths explicitly.

The reason why I'm not prefixing the callback paths automatically is because they are part of your own application. In other words the callback paths are not part of the Grant middleware, so the user shouldn't be forced to use the prefix there.

You can pull master and test if you want, in this case use the [Alternative Require](https://github.com/simov/grant#alternative-require) to require your fork.

Let me know what do you think.

**Comment by arjanfrans** [comment]
Looks good, I just tried it and it works. I agree on the automatic prefix on the callbacks, it is more flexible this way.

Thanks!

**Comment by simov** [comment]
Version 3.6.0 is published.
