### ISSUE TITLE
Splits koa express hapi 

### ISSUE THREAD

**Issue by fundon** [simov/grant#7]
Use family name:
- `grant-koa`
- `grant-express`
-...

The `grant` just is a core oauth engine.

**Comment by simov** [comment]
I know, and you're right, I'm still thinking about it. From a maintenance point of view it's easier for me to have everything in one place, because each separate consumer (express, koa and hapi) is a single file anyway, so I can keep them and their (consumer) tests in sync more easily.

Right now the only problem I'm seeing is that you have to download all of the dependencies for all of the 3 available consumers when installing grant, no matter which one you are going to use. And I don't think using peerDependencies would work either https://github.com/simov/grant/issues/5

**Comment by simov** [comment]
@fundon I think I'm getting your point, I can still keep the entire code base in one place, but I can create 3 separate meta modules, just for holding their dependencies :+1:

**Comment by simov** [comment]
Just released version 3.0.0 https://github.com/simov/grant/releases/tag/3.0.0

**Comment by fundon** [comment]
Nice :+1:

**Comment by simov** [comment]
@fundon check out the latest changelog here https://github.com/simov/grant/blob/master/CHANGELOG.md now Grant is even more loosely coupled with its dependencies allowing you to use any session store you want.
