### ISSUE TITLE
koa2 version runs only in node 8+

### ISSUE THREAD

**Issue by andreagentili** [simov/grant#76]
This is due to the use of [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original), added in node 8.0.0.

**Comment by simov** [comment]
Yes I know, in fact I have stated that in the [changelog](https://github.com/simov/grant/blob/master/CHANGELOG.md#v380-20170607).

My thinking was that `async/await` was introduced in Koa 2 with a minor version, so I though most of the people on Node 7.6 will most probably jump on the LTS Node 8.

Otherwise I could have used other method of course. Do you think that's a huge problem? I really don't know.

**Comment by andreagentili** [comment]
Not much of a problem, but I think reading this issue can save some headaches to many people.
