### ISSUE TITLE
Koa 2 examples (with current Koa API)

### ISSUE THREAD

**Issue by ryanlabouve** [simov/grant#89]
Thank you for all the great examples! I had to make some modification to get with `"koa": "^2.5.0"`.

I would be happy to add something like this as an additional example if it would be helpful:

(I also left comments on what I had to change)

```javascript
const Koa = require('koa');

const session = require('koa-session');
const Router = require('koa-router'); // New style of router
const mount = require('koa-mount');
const accesslog = require('koa-accesslog');

const Grant = require('grant-koa');
const grant = new Grant(require('./config.json'));

const app = new Koa(); // Must use new keyword
const router = new Router(); // New version of the router

require('koa-qs')(app); // This must happen via require instead of middleware

app.use(accesslog());

// REQUIRED:
app.keys = ['grant'];
app.use(session(app));
// mount grant
app.use(mount(grant));

// Updated to use `ctx` instead of `this`
router.get('/handle_github_callback', async (ctx, next) => {
  console.log(ctx.query);
  ctx.body = JSON.stringify(ctx.query, null, 2);
});

// For the new router
app.use(router.routes()).use(router.allowedMethods());

app.listen(5001, () => {
  console.log('Koa server listening on port ' + 5001);
});
```

**Comment by simov** [comment]
I was thinking about Koa2 example at some point. Feel free to add one, I'll do my final touch on top of it. Personally I'm not a huge fan of excessive comments, because it will be much easier to spot the differences between the Koa1 and Koa2 examples if you open up the files in split view or just diff them. Also the examples follow the same style rules as the rest of the code base, you can validate your example using `npm run lint`.

**Comment by ryanlabouve** [comment]
Totally! I just added the comments for the sake of sharing the snippet here. I will cleanup and PR tonight. :)

**Comment by simov** [comment]
I've published the example [here](https://github.com/simov/grant/tree/master/examples/koa-2).

Thanks for the feedback :+1:
